#!/usr/bin/env python3
"""Retract schema-extraction results for papers whose extraction ran over the
WRONG PDF's text (misfiled-PDF blast radius, see
outputs/misfile_blast_radius_2026-09-14/SUMMARY.md).

DRY-RUN BY DEFAULT. Nothing is written unless --apply, --apply-rag, or
--restore is passed explicitly.

Why this exists: extract_schema_columns.py reads a paper's own PDF text and
nothing else (comment "Only use PDF text", ~line 2027 of that script). For
the 85 literature_ids in the blast-radius set, the PDF matched at build time
was a *different paper*, so every column that script wrote for those ids
(all eco_/pr_/gear_/imp_/d_/b_/sb_ binary columns, the eco_*_guess /
depth_* / gear_target_species / imp_* / study_type* text columns) measures
the wrong paper's text. A 0 in one of those columns is not evidence of
absence for the paper the row is nominally about, any more than a 1 is
evidence of presence; both were measured against the wrong text.

What this script does (--apply):
  - nulls those columns for the target literature_ids/rows
  - sets extraction_status = 'retracted_wrong_pdf' (a new provenance column;
    the parquet has no existing extraction-status-like column to reuse: see
    the "provenance columns" section below), plus extraction_retracted_at
    and extraction_retracted_reason
  - leaves every other row's extraction_status untouched (null), so
    never-extracted / successfully-extracted rows stay indistinguishable
    from each other on this field alone (as before), but retracted rows are
    now distinguishable from both.

Target parquet: outputs/literature_review_enriched.parquet is the ONLY
parquet in this repo that carries the extraction columns as a base/source of
truth. outputs/literature_review.parquet (the pre-extraction base, 10 cols)
does not carry them. Two further files copy the columns but are *generated*
from the enriched parquet by their own scripts (outputs/viz_data.csv via
scripts/rebuild_viz_data.py; outputs/rag/paper_filters.parquet via
scripts/rag/build_filters.py) — this tool treats those as derived caches to
be regenerated, not separate targets to hand-patch, to avoid the drift
documented in ~/.claude/.../memory/feedback_corpus_figures_sync.md. Dry-run
reports their presence and current values so you know they need a rebuild
after --apply; it does not touch them. Pass --targets explicitly to add a
file as a direct write target instead.

outputs/meeting_review/enriched_schema_for_plots.csv ALSO copies these
columns and is read by visualize_issue2_schema_plots.R and
visualize_cross_schema_extra.R, but (checked 2026-09-14) NO script in this
repo writes that filename — its mtime is 2026-03-15, six months stale, and
scripts/build_meeting_review_outputs.py (the plausibly-named candidate)
writes different files entirely (missing_papers_*_summary.csv). Dry-run
still reports it (with a warning, not a regen command) so you know those two
R scripts are reading a stale, now-partly-contaminated-then-retracted file
with no known way to refresh it short of finding/rewriting its generator.

Usage:
    # dry run (default) against the blast-radius list
    python3 scripts/retract_wrong_pdf_extractions.py

    # after reviewing the dry run, apply with the exact counts it reported
    python3 scripts/retract_wrong_pdf_extractions.py --apply \\
        --expected-ids 85 --expected-rows 101

    # RAG index: dry-run chunk counts, then remove
    python3 scripts/retract_wrong_pdf_extractions.py --rag
    python3 scripts/retract_wrong_pdf_extractions.py --apply-rag \\
        --expected-ids 85

    # undo
    python3 scripts/retract_wrong_pdf_extractions.py \\
        --restore outputs/retractions/<run_id>/snapshot.json
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import shutil
import sys
import tempfile
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_IDS_CSV = (
    PROJECT_ROOT / "outputs/misfile_blast_radius_2026-09-14/blast_radius.csv"
)
DEFAULT_ID_COLUMN = "literature_id"
DEFAULT_REASON = (
    "misfiled PDF: extraction ran over the wrong paper's text "
    "(outputs/misfile_blast_radius_2026-09-14/SUMMARY.md, REVISED RECOMMENDATION)"
)

ENRICHED_PARQUET = PROJECT_ROOT / "outputs/literature_review_enriched.parquet"
RETRACTIONS_DIR = PROJECT_ROOT / "outputs/retractions"

# Derived exports that copy extraction columns from ENRICHED_PARQUET but are
# regenerated by their own scripts. Reported in dry-run, never written here
# unless explicitly named in --targets. A None command means "no known
# generator" (see the docstring) — report it as stale, don't claim a fix.
DERIVED_EXPORTS = [
    (PROJECT_ROOT / "outputs/viz_data.csv",
     "python3 scripts/rebuild_viz_data.py"),
    (PROJECT_ROOT / "outputs/rag/paper_filters.parquet",
     "/home/simon/.venvs/fashion-clip/bin/python scripts/rag/build_filters.py"),
    (PROJECT_ROOT / "outputs/meeting_review/enriched_schema_for_plots.csv",
     None),
]

PROVENANCE_COLS = [
    "extraction_status",
    "extraction_retracted_at",
    "extraction_retracted_reason",
]
RETRACTED_STATUS = "retracted_wrong_pdf"

# ---------------------------------------------------------------------------
# Column list: derived from scripts/extract_schema_columns.py itself, not by
# prefix-guessing. The 166 binary schema columns come straight from that
# script's ALL_SCHEMAS. The 14 "extra" columns are every other key
# process_paper() ever writes (verified against both its no-PDF-text branch,
# ~L2039-2057, and its PDF-text branch, ~L2102-2155, of extract_schema_columns.py
# as read 2026-09-14) — they are not in ALL_SCHEMAS because they are
# derived/text values, not binary keyword-scored columns, but they are
# computed from the SAME (possibly wrong) full_text and so are just as
# contaminated.
# ---------------------------------------------------------------------------

EXTRA_COLUMNS = [
    "eco_1_guess", "eco_2_guess", "eco_3_guess",
    "depth_range", "depth_min_m", "depth_max_m",
    "gear_target_species",
    "imp_is_bycatch", "imp_direction", "imp_quantified", "imp_confidence",
    "study_type", "study_type_signal", "study_type_evidence",
]


def get_binary_columns() -> list[str]:
    """Import extract_schema_columns.py and read ALL_SCHEMAS directly."""
    sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
    import extract_schema_columns as esc  # noqa: E402

    return [col.name for schema in esc.ALL_SCHEMAS for col in schema.columns]


def get_target_columns() -> list[str]:
    return get_binary_columns() + EXTRA_COLUMNS


# ---------------------------------------------------------------------------
# ID list loading + row matching
# ---------------------------------------------------------------------------

def load_ids(csv_path: Path, id_column: str) -> list[str]:
    df = pd.read_csv(csv_path, dtype=str)
    if id_column not in df.columns:
        raise SystemExit(
            f"Column {id_column!r} not found in {csv_path}. "
            f"Available columns: {list(df.columns)}"
        )
    ids = df[id_column].dropna()
    ids = ids[ids.str.strip() != ""]
    # normalise "12345.0" -> "12345", strip whitespace
    normed = sorted({_norm_id(v) for v in ids})
    return normed


def _norm_id(v: Any) -> str:
    s = str(v).strip()
    if s.endswith(".0") and s[:-2].isdigit():
        s = s[:-2]
    return s


def row_mask(df: pd.DataFrame, ids: list[str], id_col: str = "literature_id") -> pd.Series:
    normed = df[id_col].map(_norm_id)
    return normed.isin(set(ids))


# ---------------------------------------------------------------------------
# Timestamped backups + atomic writes
# ---------------------------------------------------------------------------

def _run_id() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def backup_file(path: Path, dest_dir: Path) -> Path:
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / path.name
    shutil.copy2(path, dest)
    return dest


def atomic_write_parquet(df: pd.DataFrame, path: Path) -> None:
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp.parquet")
    os.close(fd)
    try:
        df.to_parquet(tmp, index=False)
        os.replace(tmp, path)
    except Exception:
        Path(tmp).unlink(missing_ok=True)
        raise


def atomic_write_bytes(data: bytes, path: Path) -> None:
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)
        os.replace(tmp, path)
    except Exception:
        Path(tmp).unlink(missing_ok=True)
        raise


def atomic_write_text(text: str, path: Path) -> None:
    atomic_write_bytes(text.encode("utf-8"), path)


# ---------------------------------------------------------------------------
# JSON-safe value coercion (for snapshot old-values + restore)
# ---------------------------------------------------------------------------

def _rel(path: Path) -> Path:
    """path relative to PROJECT_ROOT for display, or the path itself if it
    lives outside the project (e.g. a test's tmp_path target)."""
    try:
        return path.relative_to(PROJECT_ROOT)
    except ValueError:
        return path


def _to_jsonable(v: Any) -> Any:
    if v is None:
        return None
    try:
        if pd.isna(v):
            return None
    except (TypeError, ValueError):
        pass
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating,)):
        return float(v)
    if isinstance(v, (np.bool_,)):
        return bool(v)
    if isinstance(v, (int, float, bool, str)):
        return v
    return str(v)


# ---------------------------------------------------------------------------
# Dry run / apply for parquet+csv targets
# ---------------------------------------------------------------------------

@dataclass
class TargetReport:
    path: Path
    exists: bool
    n_ids_matched: int = 0
    n_rows_matched: int = 0
    ids_not_found: list[str] | None = None
    dup_id_rows: dict[str, int] | None = None
    nonnull_counts: dict[str, int] | None = None
    status_counts: dict[str, int] | None = None


def read_target(path: Path) -> pd.DataFrame:
    if path.suffix == ".parquet":
        return pd.read_parquet(path)
    return pd.read_csv(path, dtype=str, low_memory=False)


def inspect_target(path: Path, ids: list[str], columns: list[str]) -> tuple[TargetReport, pd.DataFrame | None]:
    if not path.exists():
        return TargetReport(path=path, exists=False), None

    df = read_target(path)
    if "literature_id" not in df.columns:
        return TargetReport(path=path, exists=True), df

    mask = row_mask(df, ids)
    matched = df.loc[mask]
    matched_ids = set(matched["literature_id"].map(_norm_id))
    ids_not_found = sorted(set(ids) - matched_ids)
    dup_counts = matched["literature_id"].map(_norm_id).value_counts()
    dup_id_rows = {k: int(v) for k, v in dup_counts.items() if v > 1}

    present_cols = [c for c in columns if c in df.columns]
    nonnull_counts: dict[str, int] = {}
    for c in present_cols:
        col = matched[c]
        if pd.api.types.is_numeric_dtype(col) or pd.api.types.is_bool_dtype(col):
            n = int(((col.notna()) & (col != 0) & (col != False)).sum())  # noqa: E712
        else:
            n = int((col.notna() & (col.astype(str).str.strip() != "") & (col.astype(str) != "0") & (col.astype(str) != "not stated") & (col.astype(str).str.lower() != "false")).sum())
        if n:
            nonnull_counts[c] = n

    status_counts = {}
    if "extraction_status" in df.columns:
        vc = matched["extraction_status"].fillna("<null>").value_counts()
        status_counts = {str(k): int(v) for k, v in vc.items()}

    report = TargetReport(
        path=path,
        exists=True,
        n_ids_matched=len(matched_ids),
        n_rows_matched=int(mask.sum()),
        ids_not_found=ids_not_found,
        dup_id_rows=dup_id_rows,
        nonnull_counts=nonnull_counts,
        status_counts=status_counts,
    )
    return report, df


def print_target_report(report: TargetReport, present_cols: list[str], total_cols: int) -> None:
    print(f"\n=== {_rel(report.path)} ===")
    if not report.exists:
        print("  MISSING — skipped")
        return
    print(f"  ids matched:  {report.n_ids_matched}")
    print(f"  rows matched: {report.n_rows_matched}")
    if report.dup_id_rows:
        print(f"  ids with >1 row: {len(report.dup_id_rows)} "
              f"(e.g. {list(report.dup_id_rows.items())[:5]})")
    if report.ids_not_found:
        print(f"  IDS NOT FOUND IN THIS FILE ({len(report.ids_not_found)}): "
              f"{report.ids_not_found[:20]}"
              f"{' ...' if len(report.ids_not_found) > 20 else ''}")
    print(f"  target columns present in file: {len(present_cols)}/{total_cols}")
    if report.status_counts:
        print(f"  current extraction_status among matched rows: {report.status_counts}")
    if report.nonnull_counts:
        n_cells = sum(report.nonnull_counts.values())
        print(f"  columns with >=1 currently non-null/non-zero value among "
              f"matched rows: {len(report.nonnull_counts)} "
              f"({n_cells} cells total)")
        top = sorted(report.nonnull_counts.items(), key=lambda kv: -kv[1])[:25]
        for col, n in top:
            print(f"    {col:32s} {n:>4d}")
        if len(report.nonnull_counts) > 25:
            print(f"    ... and {len(report.nonnull_counts) - 25} more columns")
    else:
        print("  (no currently non-null/non-zero values among matched rows "
              "— nothing would visibly change)")


def dry_run(args: argparse.Namespace, ids: list[str], columns: list[str]) -> None:
    print(f"Loaded {len(ids)} distinct literature_ids from {args.ids_csv}")
    print(f"Reason: {args.reason}")
    print(f"\nTarget columns ({len(columns)} total = "
          f"{len(get_binary_columns())} binary schema cols + "
          f"{len(EXTRA_COLUMNS)} extra text/derived cols):")
    for c in columns:
        print(f"  {c}")

    reports = []
    for target_path in args.targets:
        report, _ = inspect_target(target_path, ids, columns)
        present_cols = []
        if report.exists:
            df = read_target(target_path)
            present_cols = [c for c in columns if c in df.columns]
        print_target_report(report, present_cols, len(columns))
        reports.append(report)

    primary = reports[0]
    print("\n=== Derived exports (reported only — regenerate, don't hand-patch) ===")
    for path, cmd in DERIVED_EXPORTS:
        if path in args.targets:
            continue
        if not path.exists():
            print(f"  {_rel(path)}: not present, skip")
            continue
        rep, _ = inspect_target(path, ids, columns)
        n = rep.n_rows_matched if rep.exists else 0
        if cmd:
            print(f"  {_rel(path)}: {n} rows carry these ids "
                  f"— after --apply, regenerate with: {cmd}")
        else:
            age_days = (time.time() - path.stat().st_mtime) / 86400
            print(f"  {_rel(path)}: {n} rows carry these ids "
                  f"— STALE ({age_days:.0f} days old), NO KNOWN GENERATOR "
                  f"script in this repo. Whatever reads this file "
                  f"(visualize_issue2_schema_plots.R, "
                  f"visualize_cross_schema_extra.R) is already working off "
                  f"stale, uncorrected data; --apply does not make that "
                  f"worse, but does not fix it either.")

    print("\n=== For --apply, pass exactly what was found above ===")
    print(f"  --expected-ids {primary.n_ids_matched} "
          f"--expected-rows {primary.n_rows_matched}")

    rag_dry_run(ids, quiet_header=False)


# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

def apply_run(args: argparse.Namespace, ids: list[str], columns: list[str]) -> None:
    if args.expected_ids is None or args.expected_rows is None:
        raise SystemExit(
            "--apply requires --expected-ids N --expected-rows N "
            "(run a dry run first and copy the numbers it prints under "
            "'For --apply, pass exactly what was found above')."
        )

    run_id = _run_id()
    run_dir = RETRACTIONS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    backups_dir = run_dir / "backups"

    snapshot: dict[str, Any] = {
        "run_id": run_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "ids_csv": str(args.ids_csv),
        "id_column": args.id_column,
        "reason": args.reason,
        "n_ids": len(ids),
        "columns": columns,
        "targets": [],
    }

    now_iso = datetime.now(timezone.utc).isoformat()

    for target_path in args.targets:
        if not target_path.exists():
            raise SystemExit(f"Target does not exist: {target_path}")

        df = read_target(target_path)
        if "literature_id" not in df.columns:
            raise SystemExit(f"{target_path} has no literature_id column — cannot target it")

        mask = row_mask(df, ids)
        matched_idx = df.index[mask]
        matched_ids_found = set(df.loc[mask, "literature_id"].map(_norm_id))

        n_ids_matched = len(matched_ids_found)
        n_rows_matched = int(mask.sum())

        if target_path == args.targets[0]:
            if n_ids_matched != args.expected_ids or n_rows_matched != args.expected_rows:
                raise SystemExit(
                    f"REFUSING: expected {args.expected_ids} ids / "
                    f"{args.expected_rows} rows but found {n_ids_matched} ids / "
                    f"{n_rows_matched} rows matched in {target_path}. "
                    "Re-run the dry run and check nothing changed "
                    "(new sync, new extraction run, wrong CSV) before retrying."
                )

        present_cols = [c for c in columns if c in df.columns]
        for c in PROVENANCE_COLS:
            if c not in df.columns:
                df[c] = None

        # Snapshot BEFORE mutating, one row per matched dataframe row.
        target_rows_snapshot = []
        for idx in matched_idx:
            row = df.loc[idx]
            old_values = {c: _to_jsonable(row[c]) for c in present_cols}
            for c in PROVENANCE_COLS:
                old_values[c] = _to_jsonable(row[c])
            target_rows_snapshot.append({
                "row_index": int(idx),
                "literature_id": _norm_id(row["literature_id"]),
                "old_values": old_values,
            })

        backup_path = backup_file(target_path, backups_dir)

        # Null the extraction columns for matched rows. bool-dtype columns
        # (e.g. imp_quantified) can't hold NaN in place without pandas
        # upcasting; do that explicitly (object dtype) rather than let it
        # warn/eventually error. int/float columns upcast to float64 fine.
        for c in present_cols:
            if pd.api.types.is_bool_dtype(df[c]):
                df[c] = df[c].astype(object)
            df.loc[matched_idx, c] = None

        # Provenance: don't clobber an already-retracted row's timestamp/reason
        # (idempotency) — only set them where extraction_status isn't already
        # RETRACTED_STATUS.
        already_retracted = df.loc[matched_idx, "extraction_status"] == RETRACTED_STATUS
        fresh_idx = matched_idx[~already_retracted.values]
        if len(fresh_idx):
            df.loc[fresh_idx, "extraction_status"] = RETRACTED_STATUS
            df.loc[fresh_idx, "extraction_retracted_at"] = now_iso
            df.loc[fresh_idx, "extraction_retracted_reason"] = args.reason

        if target_path.suffix == ".parquet":
            atomic_write_parquet(df, target_path)
        else:
            fd, tmp = tempfile.mkstemp(dir=str(target_path.parent), suffix=".tmp.csv")
            os.close(fd)
            df.to_csv(tmp, index=False)
            os.replace(tmp, target_path)

        n_fresh = len(fresh_idx)
        n_already = len(matched_idx) - n_fresh
        print(f"{_rel(target_path)}: nulled {len(present_cols)} "
              f"columns x {n_rows_matched} rows ({n_fresh} newly retracted, "
              f"{n_already} already retracted — idempotent no-op). "
              f"Backup: {_rel(backup_path)}")

        snapshot["targets"].append({
            "path": str(_rel(target_path)),
            "backup_path": str(_rel(backup_path)),
            "columns_nulled": present_cols,
            "rows": target_rows_snapshot,
        })

    snapshot_path = run_dir / "snapshot.json"
    atomic_write_text(json.dumps(snapshot, indent=2, ensure_ascii=False), snapshot_path)
    print(f"\nSnapshot written: {_rel(snapshot_path)}")
    print(f"Restore with: python3 scripts/retract_wrong_pdf_extractions.py "
          f"--restore {_rel(snapshot_path)}")
    print("\nDerived exports now stale — regenerate:")
    for path, cmd in DERIVED_EXPORTS:
        if not path.exists():
            continue
        if cmd:
            print(f"  {cmd}")
        else:
            print(f"  {_rel(path)}: no known generator — see dry-run output")


# ---------------------------------------------------------------------------
# Restore
# ---------------------------------------------------------------------------

def restore_run(snapshot_path: Path) -> None:
    snapshot = json.loads(snapshot_path.read_text())
    for target in snapshot["targets"]:
        path = PROJECT_ROOT / target["path"]
        if not path.exists():
            print(f"SKIP (missing): {path}")
            continue
        df = read_target(path)
        mismatches = []
        for row in target["rows"]:
            idx = row["row_index"]
            if idx not in df.index:
                mismatches.append((idx, "row_index no longer present"))
                continue
            current_id = _norm_id(df.at[idx, "literature_id"])
            if current_id != row["literature_id"]:
                mismatches.append((idx, f"literature_id now {current_id!r}, "
                                          f"expected {row['literature_id']!r}"))
        if mismatches:
            raise SystemExit(
                f"REFUSING to restore {path}: {len(mismatches)} row(s) shifted "
                f"since the snapshot was taken (file structure changed). "
                f"First mismatch: {mismatches[0]}"
            )

        for row in target["rows"]:
            idx = row["row_index"]
            for col, val in row["old_values"].items():
                if col not in df.columns:
                    df[col] = None
                df.at[idx, col] = val

        if path.suffix == ".parquet":
            atomic_write_parquet(df, path)
        else:
            fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp.csv")
            os.close(fd)
            df.to_csv(tmp, index=False)
            os.replace(tmp, path)
        print(f"Restored {len(target['rows'])} rows in {_rel(path)}")


# ---------------------------------------------------------------------------
# RAG index
# ---------------------------------------------------------------------------

def _rag_paths() -> dict[str, Path]:
    rag_dir = PROJECT_ROOT / "outputs/rag"
    return {
        "chunks": rag_dir / "chunks_meta.jsonl",
        "embeddings": rag_dir / "embeddings.npy",
        "index": rag_dir / "index.faiss",
        "attempt_log": rag_dir / "pdf_attempt_log.csv",
    }


def rag_dry_run(ids: list[str], quiet_header: bool = True) -> dict[str, int]:
    paths = _rag_paths()
    if not paths["chunks"].exists():
        print("\n=== RAG index ===\n  chunks_meta.jsonl missing — skipping")
        return {}

    id_set = set(ids)
    counts: dict[str, int] = {}
    total = 0
    with open(paths["chunks"], encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            d = json.loads(line)
            lid = _norm_id(d.get("literature_id"))
            if lid in id_set:
                counts[lid] = counts.get(lid, 0) + 1
                total += 1

    print("\n=== RAG index (outputs/rag/) ===")
    print(f"  ids with >=1 chunk: {len(counts)}/{len(ids)}")
    print(f"  total chunks that would be removed: {total}")
    for lid in sorted(counts, key=lambda x: -counts[x])[:15]:
        print(f"    {lid:>10s}  {counts[lid]:>4d} chunks")
    if len(counts) > 15:
        print(f"    ... and {len(counts) - 15} more ids")
    print(f"  For --apply-rag: --expected-ids {len(counts)}")
    print("  Removal method: outputs/rag/index.faiss is a flat IndexFlatIP "
          "(no clustering/training, ids are just row position). Surgical "
          "removal is safe here: filter chunks_meta.jsonl + embeddings.npy "
          "in lockstep, then rebuild the flat index from what remains "
          "(cheap: no re-embedding). --apply-rag does exactly that.")
    return counts


def rag_apply(ids: list[str], expected_ids: int | None) -> None:
    paths = _rag_paths()
    if not paths["chunks"].exists():
        raise SystemExit("outputs/rag/chunks_meta.jsonl missing — nothing to remove")

    counts = rag_dry_run(ids)
    if expected_ids is not None and len(counts) != expected_ids:
        raise SystemExit(
            f"REFUSING: expected {expected_ids} ids with chunks, found {len(counts)}."
        )

    # Import BEFORE any write: on 2026-09-14 a run under system python wrote the
    # filtered chunks and embeddings, then died here, leaving index.faiss stale.
    import faiss  # requires the fashion-clip venv

    id_set = set(ids)
    chunks = []
    keep_mask = []
    with open(paths["chunks"], encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            d = json.loads(line)
            lid = _norm_id(d.get("literature_id"))
            keep = lid not in id_set
            chunks.append(d)
            keep_mask.append(keep)
    keep_mask = np.array(keep_mask, dtype=bool)

    embeddings = np.load(paths["embeddings"])
    if len(embeddings) != len(chunks):
        raise SystemExit(
            f"REFUSING: embeddings.npy has {len(embeddings)} rows but "
            f"chunks_meta.jsonl has {len(chunks)} — files are out of sync, "
            "not safe to filter positionally."
        )

    run_id = _run_id()
    run_dir = RETRACTIONS_DIR / run_id / "rag_backups"
    run_dir.mkdir(parents=True, exist_ok=True)
    for name, p in paths.items():
        if p.exists():
            backup_file(p, run_dir)

    n_removed = int((~keep_mask).sum())
    kept_chunks = [c for c, k in zip(chunks, keep_mask) if k]
    kept_embeddings = embeddings[keep_mask]

    tmp_chunks = paths["chunks"].with_suffix(".tmp.jsonl")
    with open(tmp_chunks, "w", encoding="utf-8") as f:
        for c in kept_chunks:
            f.write(json.dumps(c, ensure_ascii=False) + "\n")
    os.replace(tmp_chunks, paths["chunks"])

    tmp_emb = paths["embeddings"].with_suffix(".tmp.npy")
    np.save(tmp_emb, kept_embeddings)
    os.replace(tmp_emb, paths["embeddings"])

    index = faiss.IndexFlatIP(kept_embeddings.shape[1])
    index.add(kept_embeddings)
    tmp_index = str(paths["index"]) + ".tmp"
    faiss.write_index(index, tmp_index)
    os.replace(tmp_index, paths["index"])

    if paths["attempt_log"].exists():
        rows = []
        with open(paths["attempt_log"], newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            fieldnames = reader.fieldnames
            for row in reader:
                if row.get("status") == "indexed" and _norm_id(row.get("literature_id")) in id_set:
                    row["status"] = RETRACTED_STATUS
                rows.append(row)
        tmp_log = paths["attempt_log"].with_suffix(".tmp.csv")
        with open(tmp_log, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            w.writerows(rows)
        os.replace(tmp_log, paths["attempt_log"])

    print(f"\nRemoved {n_removed} chunks for {len(counts)} ids. "
          f"Index now covers {len({c['literature_id'] for c in kept_chunks})} "
          f"papers / {len(kept_chunks)} chunks.")
    print(f"Backups: {_rel(run_dir)}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ids-csv", type=Path, default=DEFAULT_IDS_CSV)
    ap.add_argument("--id-column", default=DEFAULT_ID_COLUMN)
    ap.add_argument("--reason", default=DEFAULT_REASON)
    ap.add_argument("--targets", type=Path, nargs="+", default=[ENRICHED_PARQUET],
                     help="Files to write on --apply (default: the enriched "
                          "parquet only). Derived exports are reported, not "
                          "written, unless listed here explicitly.")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--expected-ids", type=int, default=None)
    ap.add_argument("--expected-rows", type=int, default=None)
    ap.add_argument("--restore", type=Path, default=None, metavar="SNAPSHOT_JSON")
    ap.add_argument("--rag", action="store_true", help="dry-run the RAG chunk count only")
    ap.add_argument("--apply-rag", action="store_true")
    args = ap.parse_args()

    if args.restore:
        restore_run(args.restore)
        return 0

    ids = load_ids(args.ids_csv, args.id_column)
    columns = get_target_columns()

    if args.apply_rag:
        rag_apply(ids, args.expected_ids)
        return 0

    if args.rag:
        rag_dry_run(ids)
        return 0

    if args.apply:
        apply_run(args, ids, columns)
        return 0

    dry_run(args, ids, columns)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
